# Tabla de Contenidos

* [Contenidos](#Tabla-de-Contenidos)
    * [Matrices](#Matrices)
        * [Importar librerías externas](#Importar-librerías-externas)
        * [De listas de listas a matrices](#De-listas-de-listas-a-matrices)
        * [Tamaño de la matriz](#Tamaño-de-la-matriz)
        * [Acceso por índices](#Acceso-por-índices)
            * [Acceso a elementos](#Acceso-a-elementos)
            * [Acceso a filas](#Acceso-a-filas)
            * [Acceso a columnas](#Acceso-a-columnas)
        * [Submatrices](#Submatrices)
        * [Archivos](#Archivos)
            * [Carga de datos](#Carga-de-datos)
* [Ejercicios](#Ejercicios)

## Matrices

Las matrices son una estructura de datos bidimencional donde los elementos se organizan en filas y columnas. Python no tiene soporte integrado para matrices; sin embargo, [NumPy](https://numpy.org/) permite el manejo de matrices como **lista dentro de listas**.

Ejemplo de esto: 

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/matriz.webp?raw=true" width="40%">
    Fuente: <a href="https://pythondiario.com/2019/01/matrices-en-python-y-numpy.html">Matrices en Python y NumPy</a>
</div>

Esta matriz es una matriz de 3x4 porque tiene 3 filas y 4 columnas. 

Revise la documentación en [NumPy documentation](https://numpy.org/doc/stable/).

## Importar librerías externas


In [1]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt

import numpy as np
import matplotlib.pyplot as plt

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
import numpy as np
import matplotlib.pyplot as plt
  </code></pre>
</details> 

## De listas de listas a matrices

Para crear [una matriz a partir de una lista de listas](https://www.geeksforgeeks.org/convert-python-nested-lists-to-multidimensional-numpy-arrays/), utilizaremos la función **array**.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_lol.png?raw=true" width="40%" style="float: left">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_mat.png?raw=true" width="35%">
</div>


In [2]:
listaDeLista = [[1, 4, 5], [-5, 8, 9]]

# Asigne a la variable matriz, use la función array para convertir listaDeLista 

matriz = np.array(listaDeLista)

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
matriz = np.array( listaDeLista )
  </code></pre>
</details> 

In [3]:
# Muestre por pantalla la listaDeLista

print("Lista de lista")
print(listaDeLista)

Lista de lista
[[1, 4, 5], [-5, 8, 9]]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print("Lista de lista")
print(listaDeLista)
  </code></pre>
</details> 

In [4]:
# Muestre por pantalla la matriz

print("Matriz")
print(matriz)

Matriz
[[ 1  4  5]
 [-5  8  9]]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print("Matriz")
print(matriz)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Tamaño de la matriz

De cada matriz es posible obtener la **cantidad de filas** y la **cantidad de columnas** con la propiedad [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html), como se muestra en la figura: 


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_shape.png?raw=true" width="30%">
</div>


In [6]:
# Obtenga el tamaño de la matriz y muestre por pantalla el resultado


tamanio = matriz.shape
print(f"Tamaño: {tamanio}")

Tamaño: (2, 3)


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
tamanio = matriz.shape
print(f"Tamaño: {tamanio}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Acceso por índices

Numpy utiliza la notación por índices en las **filas** y en las **columnas** para acceder a un elemento o a un grupo de elementos en una matriz.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>



### Acceso a elementos

Dada la matriz:

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>

Para acceder al valor **5** en la matriz, debe colocar:

* **Índice de la fila**: _1_, y 
* **Índice de la columna**: _2_.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_ele12.png?raw=true" width="40%">
</div>

In [7]:
# Considere la matriz

print("Matriz")
print(matriz)

Matriz
[[ 1  4  5]
 [-5  8  9]]


In [8]:
# Obtenga y muestre el elemento en la fila 0, columna 2

print(matriz[0,2])

5


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
elemento = matriz[0,2]
print(f"Elemento matriz[0,2]: {elemento}")
  </code></pre>
</details> 

In [9]:
# Obtenga y muestre el elemento en la fila 1, columna 1

print(matriz[1,1])

8


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
elemento = matriz[1,1]
print(f"Elemento matriz[1,1]: {elemento}")
  </code></pre>
</details> 

In [10]:
# Obtenga y muestre el elemento en la fila 0, columna 1

print(matriz[0,1])

4


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
elemento = matriz[0,1]
print(f"Elemento matriz[0,1]: {elemento}")
  </code></pre>
</details> 

In [11]:
# Obtenga y muestre el elemento en la fila 1, columna 0

print(matriz[1,0])

-5


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
elemento = matriz[1,0]
print("Elemento matriz[1,0]: ",elemento)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Acceso a filas

Dada la matriz:

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>

Para acceder a la fila **0** de la matriz, debe colocar:

* **Índice de la fila**: _0_, y 
* **Índice de todas las columnas**: desde 0 hasta el final ( _0:_ ).

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_fila0.png?raw=true" width="30%">
</div>


In [12]:
# Considere la matriz

print("Matriz")
print(matriz)

Matriz
[[ 1  4  5]
 [-5  8  9]]


In [16]:
# Obtenga y muestre la fila 0 de la matriz

fila0 = matriz[ 0 , 0:]
print(f"Fila 0: {fila0}")

Fila 0: [1 4 5]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
fila0 = matriz[ 0 , 0:]
print(f"Fila 0: {fila0}")
  </code></pre>
</details> 

In [15]:
# Obtenga y muestre la fila 1 de la matriz

fila1 = matriz[ 1 , 0:]
print(f"Fila 1: {fila1}")

Fila 1: [-5  8  9]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
fila1 = matriz[ 1 , 0:]
print(f"Fila 1: {fila1}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Acceso a columnas

Dada la matriz:

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>

Para acceder a la columna **1** de la matriz, debe colocar:

* **Índice de todas las filas**: desde 0 hasta el final ( _0:_ ), y 
* **Índice de la columna**: _1_.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_columna1.png?raw=true" width="30%">
</div>


In [13]:
# Considere la matriz

print("Matriz")
print(matriz)

Matriz
[[ 1  4  5]
 [-5  8  9]]


In [14]:
# Muestre cada una de las columnas de matriz por separado

columna0 = matriz[ 0: , 0]
print(f"Columna 0: {columna0}")

columna1 = matriz[ 0: , 1]
print(f"Columna 1: {columna1}")


columna2 = matriz[ 0: , 2]
print(f"Columna 2: {columna2}")

Columna 0: [ 1 -5]
Columna 1: [4 8]
Columna 2: [5 9]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
columna0 = matriz[ 0: , 0]
print(f"Columna 0: {columna0}")

columna1 = matriz[ 0: , 1]
print(f"Columna 1: {columna1}")

columna2 = matriz[ 0: , 2]
print(f"Columna 2: {columna2}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Submatrices

Dada la matriz:

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>

Para acceder a la submatriz conformada por las **dos primeras filas** y las **dos primeras columnas**, debe colocar:

* **Índice de todas las filas**: desde 0 hasta el final ( _0:2_ ), y 
* **Índice de las dos primeras columnas**: desde 0 hasta 2 ( _0:2_ ).

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_matrix0.png?raw=true" width="30%">
</div>



In [17]:
# Considere la matriz

print("Matriz")
print(matriz)

Matriz
[[ 1  4  5]
 [-5  8  9]]


In [18]:
# Muestre la submatriz conformada por las dos primeras filas y las dos primeras columnas 

submatriz1 = matriz[ 0:2, 0:2 ]
print("Primera submatriz")
print(submatriz1)

Primera submatriz
[[ 1  4]
 [-5  8]]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
submatriz1 = matriz[ 0: , 0:2 ]
print("Primera submatriz")
print(submatriz1)
  </code></pre>
</details> 

In [20]:
# Muestre la submatriz conformada por las dos últimas filas y las dos últimas columnas 


submatriz2 = matriz[ 0: , 1: ]
print("Segunda submatriz")
print(submatriz2)

Segunda submatriz
[[4 5]
 [8 9]]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
submatriz2 = matriz[ 0: , 1: ]
print("Segunda submatriz")
print(submatriz2)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Archivos

Descargue los archivos [songs.csv](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/songs.csv) y [votes.csv](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/votes.csv). Luego, coloque los archivos csv en el mismo directorio que este cuaderno.

## Carga de datos


Utilice la función [loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) para cargar los datos de un archivo de texto.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_load1.png?raw=true" width="50%">
</div>


In [21]:
# En la variable canciones, use np.loadtxt para cargar los datos de 'songs.csv'
# Cuyo delimitador es ';' y el tipo de dato (dtype) es str

canciones = np.loadtxt('songs.csv', delimiter = ';', dtype=str)

In [46]:
# En la variable votos, use np.loadtxt para cargar los datos de 'votes.csv', 
# Cuyo delimitador es ',' y el tipo de dato (dtype) es int

votos = np.loadtxt('votes.csv', delimiter = ',', dtype=int)

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
canciones = np.loadtxt( 'songs.csv', delimiter = ';', dtype = str)
votos = np.loadtxt( 'votes.csv', delimiter = ',', dtype = int)
  </code></pre>
</details> 

In [32]:
# Muestre el arreglo canciones

print("Arreglo de canciones: ")
print(canciones)

Arreglo de canciones: 
["I Don't Care (with Justin Bieber) - Loud Luxury Remix"
 'Memories - Dillon Francis Remix' 'All the Time - Don Diablo Remix'
 'Call You Mine - Keanu Silva Remix'
 'Someone You Loved - Future Humans Remix'
 'Beautiful People (feat. Khalid) - Jack Wins Remix'
 'Never Really Over - R3HAB Remix'
 'Post Malone (feat. RANI) - GATTÃœSO Remix'
 'Tough Love - Tiësto Remix / Radio Edit'
 "If I Can't Have You - Gryffin Remix"
 'Cross Me (feat. Chance the Rapper & PnB Rock) - M-22 Remix'
 'Hate Me - R3HAB Remix' 'Body On My'
 'SOS - Laidback Luke Tribute Remix / Radio Edit'
 'Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy) - Tiësto Remix'
 'South of the Border (feat. Camila Cabello & Cardi B) - Andy Jarvis Remix'
 'All My Friends - Eden Prince Remix'
 'Say My Name (feat. Bebe Rexha & J Balvin) - Lucas & Steve Remix'
 'Dancing With A Stranger (With Normani) - Cheat Codes Remix'
 'Let It Be Me - Sondr Remix']


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print(canciones)
  </code></pre>
</details> 

In [47]:
# Muestre la matriz votos

print("Matriz de votos: ")
print("Filas (20 canciones) vs Columnas (10 votos)")
print(votos)

Matriz de votos: 
Filas (20 canciones) vs Columnas (10 votos)
[[9 2 6 6 5 3 6 3 2 3]
 [9 8 3 3 3 6 4 7 8 0]
 [9 9 5 7 2 9 6 3 2 0]
 [3 8 8 4 9 0 2 6 4 7]
 [2 6 8 3 6 4 1 1 7 5]
 [8 2 2 1 5 9 4 0 8 1]
 [7 3 9 5 1 0 2 7 7 7]
 [5 6 6 3 7 0 9 2 3 3]
 [7 8 7 0 9 0 1 6 5 5]
 [3 8 8 7 8 3 7 1 1 4]
 [5 1 4 9 8 6 1 0 7 2]
 [5 0 6 7 6 7 9 9 1 2]
 [8 2 0 7 5 3 0 8 7 2]
 [3 6 3 3 2 0 5 8 5 2]
 [2 5 0 4 7 7 2 0 5 0]
 [6 7 0 3 1 7 1 0 3 3]
 [4 6 0 6 6 6 2 8 2 6]
 [8 1 9 2 8 1 4 1 0 9]
 [9 7 3 2 0 0 6 2 0 0]
 [9 3 3 2 9 4 8 8 4 9]]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print(votos)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Ejercicios

**Ejercicio 01:** Muestre el nombre y los votos de la quinta (índice 4) canción

In [35]:
nombreQuinta = canciones[4]
votosQuinta = votos[4, 0:]

print(f"Nombre de la quinta canción {nombreQuinta}")
print(f"Votos de la quinta canción {votosQuinta}")

Nombre de la quinta canción Someone You Loved - Future Humans Remix
Votos de la quinta canción [2 6 8 3 6 4 1 1 7 5]


**Ejercicio 02:** Muestre el mínimo, el promedio y el máximo voto de la quinta  (índice 4) canción

In [38]:
minimo = np.min(votosQuinta)
promedio = np.average(votosQuinta)
maximo = np.max(votosQuinta)

print(f"Voto Mínimo de la Quinta canción: {minimo}")
print(f"Voto Promedio de la Quinta canción: {promedio}")
print(f"Voto Máximo de la Quinta canción: {maximo}")

Voto Mínimo de la Quinta canción: 1
Voto Promedio de la Quinta canción: 4.3
Voto Máximo de la Quinta canción: 8


**Ejercicio 03:** Muestre el total de votos de la primera canción

In [42]:
totalQuinta = np.sum(votos[ 0 , 0: ])

print(f"Total de votos de la primera canción: {totalQuinta}")

Total de votos de la primera canción: 45


**Ejercicio 04:** Muestre el total de votos de todas las canciones

In [43]:
total = np.sum(votos)

print(f"Total de votos: {total}")

Total de votos: 886
