## Importar librerías externas

In [ ]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt

## Arreglos y matrices 

Convierta las listas en arreglos (1-dimensión) y matrices (2-dimensiones).

In [ ]:
# Convierta las listas en arreglos

lista1 = [11, 12,  9,  3, 14,  9]
lista2 = [ 6, 11, 10, 12,  9, 10]

arreglo1 = np.array(lista1)
arreglo2 = np.array(lista2)

In [ ]:
# Convierta las listas de listas en matrices

listaDelistas1 = [[14,  5,  4, 13,  8, 14],
                  [10,  2,  9,  9,  3,  4],
                  [ 9,  4, 11,  7,  9, 13],
                  [14,  5, 14, 12, 13,  9],
                  [12,  3,  5,  5,  4,  8]]

listaDelistas2 = [[14,  6,  2,  5, 10,  8],
                  [13, 11, 14, 11,  4, 10],
                  [14, 13,  3, 14,  5,  7],
                  [ 2,  2,  8, 14,  2,  4],
                  [11,  6, 12,  3,  4,  2]]

matriz1 = np.array(listaDelistas1)
matriz2 = np.array(listaDelistas2)

## Operaciones por elementos

### Con un escalar

Numpy permite optimizar las operaciones entre [un arreglo y un escalar](https://scipy-lectures.org/intro/numpy/operations.html#id2); por ejemplo, el `arreglo3` contiene el resultado de la suma de cada elemento del `arreglo1` con `5.2`.



<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b1.png?raw=true" width="35%">
</div>

In [ ]:
# En arreglo4 asigne el resultado de sumar arreglo2 y 4. Muestre el resultado de arreglo4.

In [ ]:
# En arreglo5 asigne el resultado de multiplicar arreglo1 y 2.3. Muestre el resultado de arreglo5.

In [ ]:
# En arreglo6 asigne el resultado de restar arreglo2 y 2.3. Muestre el resultado de arreglo6.

### Entre arreglos

NumPy proporciona una amplia gama de [operaciones que se pueden realizar entre arreglos](https://www.programiz.com/python-programming/numpy/basic-array-operations). En el ejemplo, la multiplicación entre `arreglo1` y `arreglo2`ocurre entre cada elemento correspondiente, dado que tienen el mismo tamaño.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b2.png?raw=true" width="35%">
</div>


In [ ]:
# En arreglo8 asigne el resultado de dividir arreglo1 y arreglo4. Muestre el arreglo8.

In [ ]:
# En arreglo9 asigne el resultado de restar arreglo2 y arreglo5. Muestre el arreglo9.

In [ ]:
# En arreglo10 asigne el resultado de sumar arreglo5 y arreglo6. Muestre el arreglo10.

## Operaciones matriciales

NumPy provee de operaciones matriciales como suma, multiplicación y elevación de elementos a una determinada potencia. El empleo de matrices nos permite ejecutar operaciones algebraicas, lo que nos permite ejecutar numerosas operaciones con grandes cantidades de datos de manera efectiva. [How to Implement Different Operations on Matrices in NumPy?](https://www.scaler.com/topics/numpy-implement-different-operations-on-matrix/) muestran las operaciones más comunes entre matrices mediante ejemplos.

In [82]:
matriz6 = matriz1 - matriz2 

print("matriz6")
print(matriz6)

matriz6
[[ 0 -1  2  8 -2  6]
 [-3 -9 -5 -2 -1 -6]
 [-5 -9  8 -7  4  6]
 [12  3  6 -2 11  5]
 [ 1 -3 -7  2  0  6]]


### Operaciones con un escalar

En el ejemplo, la `matriz3` contiene el resultado de multiplicar `1.12` y `matriz1`, al multiplicar cada elemento por el escalar.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b3.png?raw=true" width="30%">
</div>

In [ ]:
# En matriz4 asigne el resultado de sumar matriz2 y 3.2. Muestre el matriz4.

In [ ]:
# En matriz5 asigne el resultado de dividir matriz1 para 2. Muestre el matriz5.

### Operaciones matriciales

Para matrices de igual número de filas y columnas, es posible realizar las operaciones matemáticas básicas para cada elemento de las matrices. Por ejemplo, `matriz6` contiene el resultado de restar `matriz1` y `matriz2`.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b4.png?raw=true" width="30%">
</div>

### Operaciones de todos los elementos

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b2.png?raw=true" width="35%">
</div>

### Operaciones por columnas o por filas

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b2.png?raw=true" width="35%">
</div>

## Archivos

Descargue el archivo [produccion.zip](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/produccion.zip). Descomprima la carpeta **produccion** y colóquela en el mismo directorio que este cuaderno.

## Carga de datos


Utilice la función [loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) para cargar los datos de un archivo de texto.

In [ ]:
# En la variable zonas, cargue los datos de 'produccion/zonas.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

zonas = np.loadtxt('produccion/zonas.csv', delimiter=",", dtype=str)

In [ ]:
# En la variable productos, cargue los datos de 'produccion/productos.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

productos = np.loadtxt('produccion/productos.csv', delimiter=",", dtype=str)

In [ ]:
# En las variables octubre, noviembre y diciembre, cargue los datos de cada archivo con el nombre correspondiente
# cuyo delimitador es ',' y el tipo de dato (dtype) es in

octubre = np.loadtxt('produccion/octubre.csv', delimiter=",", dtype=int)

## Ejercicios


In [ ]:
np.random.randint(2,high= 15, size=(1, 6))