## Matrices

Las matrices son una estructura de datos bidimencional donde los elementos se organizan en filas y columnas. Python no tiene soporte integrado para matrices; sin embargo, [NumPy](https://numpy.org/) permite el manejo de matrices como **lista dentro de listas**.

Ejemplo de esto: 

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/matriz.webp?raw=true" width="40%">
    Fuente: <a href="https://pythondiario.com/2019/01/matrices-en-python-y-numpy.html">Matrices en Python y NumPy</a>
</div>

Esta matriz es una matriz de 3x4 porque tiene 3 filas y 4 columnas. 

Revise la documentación en [NumPy documentation](https://numpy.org/doc/stable/).

## Importar librerías externas


In [2]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt

import numpy as np
import matplotlib.pyplot as plt

## De listas de listas a matrices

Para crear [una matriz a partir de una lista de listas](https://www.geeksforgeeks.org/convert-python-nested-lists-to-multidimensional-numpy-arrays/), utilizaremos la función **array**.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_lol.png?raw=true" width="40%">
</div>

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_mat.png?raw=true" width="35%">
</div>


In [3]:
# Utilice la función array para convertir la listaDeLista en una matriz 
# Muestre por pantalla la matriz

listaDeLista = [[1, 4, 5], [-5, 8, 9]]

matriz = np.array( listaDeLista )

print("Matriz")
print(matriz)


Matriz
[[ 1  4  5]
 [-5  8  9]]


## Acceso a elementos

Numpy utiliza la notación por índices en las **filas** y en las **columnas** para acceder a un elemento o a un grupo de elementos en una matriz.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>



### Elementos

Para acceder a un elemento, debe:

* Fila:     indexar la fila con el valor del **índice** (p.e.: _1_), y 
* Columna:     indexar la columna con el valor del **índice** (p.e.: _2_).


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_ele12.png?raw=true" width="40%">
</div>

In [4]:
# Obtenga y muestre el elemento en la fila 0, columna 2
elemento = matriz[0,2]
print("Elemento matriz[0,2]: ",elemento)

Elemento matriz[0,2]:  5


In [5]:
# Obtenga y muestre el elemento en la fila 1, columna 1
elemento = matriz[1,1]
print("Elemento matriz[1,1]: ",elemento)

Elemento matriz[1,1]:  8


In [6]:
# Obtenga y muestre el elemento en la fila 0, columna 1
elemento = matriz[0,1]
print("Elemento matriz[0,1]: ",elemento)

Elemento matriz[0,1]:  4


In [7]:
# Obtenga y muestre el elemento en la fila 1, columna 0
elemento = matriz[1,0]
print("Elemento matriz[1,0]: ",elemento)

Elemento matriz[1,0]:  -5


### Filas

Para acceder a todos los elementos en la primera fila, debe:

* Fila:     indexar la fila con el valor del **índice** (p.e.: _0_), y   
* Columna:  rebanar todas las columnas **desde inicio hasta el final** (p.e.: _0:_).

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_fila0.png?raw=true" width="30%">
</div>


In [8]:
# Obtenga y muestre la fila 0 de la matriz
fila0 = matriz[ 0 , 0:]
print("Fila0")
print(fila0)

Fila0
[1 4 5]


In [9]:
# Obtenga y muestre la fila 1 de la matriz
fila1 = matriz[ 1 , 0:]
print("Fila1")
print(fila1)

Fila1
[-5  8  9]


### Columnas

Para acceder a todos los elementos en la segunda columna, debe:

* Fila:     rebanar todas las filas **desde inicio hasta el final** (p.e.: _0:_), y   
* Columna:  indexar la columna con el valor del **índice** (p.e.: _1_).


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_columna1.png?raw=true" width="30%">
</div>


In [10]:
# Muestre todas las columna de matriz por separado
columna0 = matriz[ 0: , 0]
print("Columna0")
print(columna0)

columna1 = matriz[ 0: , 1]
print("Columna1")
print(columna1)

columna2 = matriz[ 0: , 2]
print("Columna2")
print(columna2)

Columna0
[ 1 -5]
Columna1
[4 8]
Columna2
[5 9]


### Submatrices

Para acceder a la submatriz conformada por las **dos primeras filas** y las **dos primeras columnas**, debe:

* Fila: rebanar todas las filas desde inicio hasta el final (p.e.: 0:), y
* Columna: rebanar las columnas desde inicio hasta antes de la columna 2  (p.e.: 0:2).

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_matrix0.png?raw=true" width="30%">
</div>



In [11]:
# Muestre la submatriz conformada por las dos primeras filas y las dos primeras columnas 
submatriz1 = matriz[ 0: , 0:2 ]
print("Primera submatriz")
print(submatriz1)

Primera submatriz
[[ 1  4]
 [-5  8]]


In [12]:
# Muestre la submatriz conformada por las dos últimas filas y las dos últimas columnas 
submatriz2 = matriz[ 0: , 1: ]
print("Segunda submatriz")
print(submatriz2)

Segunda submatriz
[[4 5]
 [8 9]]


## Archivos

Descargue los archivos [songs.csv](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/songs.csv) y [votes.csv](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/votes.csv). Luego, coloque los archivos csv en el mismo directorio que este cuaderno.

## Carga de datos


Utilice la función [loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) para cargar los datos de un archivo de texto.

In [13]:
# Cargue los datos de 'songs.csv', cuyo delimitador es ';' y el tipo de dato (dtype) es str
songs = np.loadtxt( 'songs.csv', delimiter = ';', dtype = str)


In [14]:
# Cargue los datos de 'votes.csv', cuyo delimitador es ',' y el tipo de dato (dtype) es int
votes = np.loadtxt( 'votes.csv', delimiter = ',', dtype = int)


## Ejercicios - I

1. Muestre el arreglo con los titulos de canciones
2. Muestre la matriz con los votos

In [15]:
print(songs.size)
print(songs)


20
["I Don't Care (with Justin Bieber) - Loud Luxury Remix"
 'Memories - Dillon Francis Remix' 'All the Time - Don Diablo Remix'
 'Call You Mine - Keanu Silva Remix'
 'Someone You Loved - Future Humans Remix'
 'Beautiful People (feat. Khalid) - Jack Wins Remix'
 'Never Really Over - R3HAB Remix'
 'Post Malone (feat. RANI) - GATTÃœSO Remix'
 'Tough Love - Tiësto Remix / Radio Edit'
 "If I Can't Have You - Gryffin Remix"
 'Cross Me (feat. Chance the Rapper & PnB Rock) - M-22 Remix'
 'Hate Me - R3HAB Remix' 'Body On My'
 'SOS - Laidback Luke Tribute Remix / Radio Edit'
 'Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy) - Tiësto Remix'
 'South of the Border (feat. Camila Cabello & Cardi B) - Andy Jarvis Remix'
 'All My Friends - Eden Prince Remix'
 'Say My Name (feat. Bebe Rexha & J Balvin) - Lucas & Steve Remix'
 'Dancing With A Stranger (With Normani) - Cheat Codes Remix'
 'Let It Be Me - Sondr Remix']


In [16]:
print(votes.shape)
print(votes)

(35, 20)
[[7 2 9 3 7 4 1 9 6 4 7 9 0 5 8 0 3 2 8 6]
 [6 8 3 6 8 1 0 0 7 6 6 1 9 5 1 2 1 9 3 9]
 [0 6 8 0 4 6 5 5 9 6 9 5 7 5 1 7 4 0 3 0]
 [0 7 3 0 7 5 7 7 3 3 8 5 8 3 6 3 9 0 7 0]
 [1 1 4 7 4 2 0 8 2 5 5 3 7 7 4 9 2 0 5 3]
 [4 2 7 5 4 5 7 8 4 1 9 8 1 9 8 9 0 4 9 5]
 [4 7 4 6 9 8 3 2 5 0 2 2 7 1 0 2 1 3 4 3]
 [6 1 7 0 7 3 8 2 1 5 0 6 1 7 0 9 3 1 9 2]
 [4 3 6 2 4 7 6 7 0 7 1 0 3 2 2 6 8 8 9 4]
 [7 0 2 9 3 4 3 5 3 2 4 9 7 8 7 5 5 3 1 6]
 [0 3 0 0 7 0 1 9 8 6 3 4 8 3 0 4 7 0 7 1]
 [3 3 2 7 3 8 8 0 3 2 5 4 1 3 2 1 6 4 5 9]
 [6 6 2 7 6 4 3 6 0 3 1 1 2 4 1 2 9 0 7 0]
 [0 8 3 3 0 0 2 0 0 4 5 1 4 5 8 8 5 1 4 2]
 [1 2 5 1 0 6 4 9 1 1 7 0 0 9 1 7 8 3 0 2]
 [9 5 5 8 9 1 5 3 7 6 7 1 4 8 0 3 7 9 8 3]
 [2 4 1 0 3 9 0 8 6 8 0 0 2 0 2 0 7 0 5 8]
 [7 5 1 9 2 5 0 1 0 4 1 3 3 8 2 9 1 1 3 6]
 [4 5 0 2 5 4 1 7 5 4 8 7 3 0 3 4 2 0 6 8]
 [8 8 5 0 2 4 8 3 5 3 0 0 5 4 0 2 4 8 2 4]
 [9 1 0 5 8 8 8 6 1 3 3 5 4 4 2 1 6 8 6 9]
 [5 7 4 6 4 7 8 2 6 7 8 4 2 3 4 1 1 0 1 2]
 [1 7 9 1 8 8 7 8 5 6 4 2 0 9 9 8 1 5 2 6]
 [

## Ejercicios - II

1. Muestre el nombre de la canción en la primera fila
2. Muestre el total de votos de en primera fila

In [19]:
print("Canción en el índice 0", songs[0])
print("Votos de la canción en el índice 0", votes[0, 0:])

Canción en el índice 0 I Don't Care (with Justin Bieber) - Loud Luxury Remix
Votos de la canción en el índice 0 [7 2 9 3 7 4 1 9 6 4 7 9 0 5 8 0 3 2 8 6]


## Ejercicios - III

1. Muestre el total de votos de todas las canciones
2. Muestre el valor mayor del total de votos de todas las canciones
3. Muestre el índice del valor mayor del total de votos de todas las canciones
4. Muestre el nombre de la canción con el valor mayor del total de votos de todas las canciones

In [21]:
total = np.sum(votes)
print("Total de votos de todas las canciones: ", total)

Total de votos de todas las canciones:  2963
