# Tabla de Contenidos

* [Contenidos](#Tabla-de-Contenidos)
    * [Importar librerías externas](#Importar-librerías-externas)
    * [Listas y Listas de listas](#Listas-y-Listas-de-listas)
        * [Limitantes de operaciones entre listas](#Limitantes-de-operaciones-entre-listas)
    * [Arreglos y matrices](#Arreglos-y-matrices)
    * [Operaciones entre arreglos y escalares](#Operaciones-entre-arreglos-y-escalares)
        * [Entre arreglos y escalares](#Entre-arreglos-y-escalares)
        * [Entre arreglos](#Entre-arreglos)
    * [Operaciones matriciales](#Operaciones-matriciales)
        * [Operaciones con un escalar](#Operaciones-con-un-escalar)
        * [Operaciones entre matrices](#Operaciones-entre-matrices)
        * [Operaciones de todos los elementos](#Operaciones-de-todos-los-elementos)
        * [Operaciones por columnas o por filas](#Operaciones-por-columnas-o-por-filas)
    * [Archivos](#Archivos)
        * [Carga de datos](#Carga-de-datos)
* [Ejercicios](#Ejercicios)

## Importar librerías externas

In [1]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt

import numpy as np
import matplotlib.pyplot as plt

## Listas y Listas de listas

In [2]:
# Cargue las listas y las listas de listas 

lista1 = [11, 12,  9,  3, 14,  9]
lista2 = [ 6, 11, 10, 12,  9, 10]


listaDelistas1 = [[14,  5,  4, 13,  8, 14],
                  [10,  2,  9,  9,  3,  4],
                  [ 9,  4, 11,  7,  9, 13],
                  [14,  5, 14, 12, 13,  9],
                  [12,  3,  5,  5,  4,  8]]

listaDelistas2 = [[14,  6,  2,  5, 10,  8],
                  [13, 11, 14, 11,  4, 10],
                  [14, 13,  3, 14,  5,  7],
                  [ 2,  2,  8, 14,  2,  4],
                  [11,  6, 12,  3,  4,  2]]

### Limitantes de operaciones entre listas

In [ ]:
# Sume elemento por elemento de la lista1 con la lista2
# Muestre el resultado por pantalla



In [ ]:
# Sume elementos por elemento de la listaDelistas1 con la listaDelistas2
# Muestre el resultado por pantalla


## Arreglos y matrices 

Convierta las listas en arreglos (1-dimensión) y matrices (2-dimensiones).

In [3]:
# Convierta las listas en arreglos y las listas de listas en matrices

arreglo1 = 
arreglo2 = 

matriz1 = 
matriz2 = 

In [ ]:
# Muestre los arreglos y las matrices



[Regresar a la TC](#Tabla-de-Contenidos)

## Operaciones entre arreglos y escalares

### Entre arreglos y escalares

Numpy permite optimizar las operaciones entre [un arreglo y un escalar](https://scipy-lectures.org/intro/numpy/operations.html#id2); por ejemplo, el `arreglo3` contiene el resultado de la suma de cada elemento del `arreglo1` con `5.2`.



<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b1.png?raw=true" width="35%">
</div>

In [ ]:
# En arreglo4 asigne el resultado de sumar arreglo2 con el número 4. 
# Muestre el arreglo2 y el arreglo4.


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo4 = arreglo2 + 4
print(f"Arreglo 2: {arreglo2} + 4")
print(f"Arreglo 4: {arreglo4}")
  </code></pre>
</details> 

In [ ]:
# En arreglo5 asigne el resultado de multiplicar arreglo1 con 2.3. 
# Muestre el arreglo1 y el arreglo5.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo5 = arreglo1 * 2.3
print(f"Arreglo 1: {arreglo1} * 2.3")
print(f"Arreglo 5: {arreglo5}")
  </code></pre>
</details> 

In [ ]:
# En arreglo6 asigne el resultado de restar arreglo2 con 2.3. 
# Muestre el arreglo2 y el arreglo6.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo6 = arreglo2 - 2.3
print(f"Arreglo 2: {arreglo2} - 2.3")
print(f"Arreglo 6: {arreglo6}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Entre arreglos

NumPy proporciona una amplia gama de [operaciones que se pueden realizar entre arreglos](https://www.programiz.com/python-programming/numpy/basic-array-operations). En el ejemplo, la multiplicación entre `arreglo1` y `arreglo2`ocurre entre cada elemento correspondiente, dado que tienen el mismo tamaño.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b2.png?raw=true" width="35%">
</div>


In [ ]:
# En arreglo8 asigne el resultado de dividir arreglo1 y arreglo4. 
# Muestre los arreglos que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo8 = arreglo1 / arreglo4 
print(f"{arreglo1} / {arreglo4}")
print(f"Arreglo 8: {arreglo8}")
  </code></pre>
</details> 

In [ ]:
# En arreglo9 asigne el resultado de restar arreglo2 y arreglo5. 
# Muestre los arreglos que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo9 = arreglo2 - arreglo5
print(f"{arreglo2} / {arreglo5}")
print(f"Arreglo 9: {arreglo9}")
  </code></pre>
</details> 

In [ ]:
# En arreglo10 asigne el resultado de sumar arreglo5 y arreglo6. 
# Muestre los arreglos que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
arreglo10 = arreglo5 + arreglo6
print(f"{arreglo5} / {arreglo6}")
print(f"Arreglo 9: {arreglo10}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Operaciones matriciales

NumPy provee de operaciones matriciales como suma, multiplicación y potenciación. El empleo de matrices nos permite ejecutar operaciones algebraicas, lo que nos permite ejecutar numerosas operaciones con grandes cantidades de datos de manera efectiva. [How to Implement Different Operations on Matrices in NumPy?](https://www.scaler.com/topics/numpy-implement-different-operations-on-matrix/) muestran las operaciones más comunes entre matrices mediante ejemplos.

### Operaciones con un escalar

En el ejemplo, la `matriz3` contiene el resultado de multiplicar `1.12` y `matriz1`, al multiplicar cada elemento por el escalar.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b3.png?raw=true" width="30%">
</div>

In [ ]:
# En matriz4 asigne el resultado de sumar 3.2 y matriz2. 
# Muestre las matrices que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
matriz4 = 3.2 + matriz2
print("3.2 + ")
print("\nMatriz 2")
print(matriz2)
print("\nMatriz 4: ")
print(matriz4)
  </code></pre>
</details> 

In [ ]:
# En matriz5 asigne el resultado de dividir matriz1 para 2. 
# Muestre las matrices que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
matriz5 = matriz1 / 2
print("Matriz 1")
print(matriz1)
print("\n/ 2")
print("\nMatriz 5: ")
print(matriz5)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Operaciones entre matrices

Para matrices de igual número de filas y columnas, es posible realizar las operaciones matemáticas básicas para cada elemento de las matrices. Por ejemplo, `matriz6` contiene el resultado de restar `matriz1` y `matriz2`.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b4.png?raw=true" width="30%">
</div>

In [ ]:
# En matriz7 asigne el resultado de sumar matriz2 y matriz1. 
# Muestre las matrices que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
matriz7 = matriz2 + matriz1
print("Matriz 2")
print(matriz2)
print("\n+")
print("\nMatriz 1")
print(matriz1)
print("\nMatriz 7: ")
print(matriz7)
  </code></pre>
</details> 

In [ ]:
# En matriz8 asigne el resultado de multiplicar matriz2 y matriz1. 
# Muestre las matrices que intervienen en la operación.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
matriz8 = matriz2 * matriz1
print("Matriz 2")
print(matriz2)
print("\n*")
print("\nMatriz 1")
print(matriz1)
print("\nMatriz 8: ")
print(matriz8)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Operaciones de todos los elementos

La función [np.sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) se utiliza para determinar la suma de todos los elementos de la matriz NumPy.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b5.png?raw=true" width="45%">
</div>

In [ ]:
# En total7 asigne el resultado de sumar todos los elementos de la matriz7. 
# Muestre la variable total7.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
total7 = np.sum(matriz7)
print(f"El total de matriz7 es: {total7}")
  </code></pre>
</details> 

In [ ]:
# En total8 asigne el resultado de sumar todos los elementos de la matriz8. 
# Muestre la variable total8.



<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
total8 = np.sum(matriz8)
print(f"El total de matriz8 es: {total8}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Operaciones de todas las columnas o de todas las filas

La función de [np.sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) NumPy tiene varios parámetros que le permiten controlar el comportamiento de la función. 

Como se muestra en la figura, para sumar:
- Todas las filas (a lo largo del eje vertical), se utiliza el parámetro `axis = 0`. 
- Todas las columnas (a lo largo del eje horizontal), se utiliza el parámetro `axis = 1`, 

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b7.png?raw=true" width="35%">
    <br>
    Fuente: <a href="https://sebastianraschka.com/blog/2020/numpy-intro.html">Scientific Computing in Python: Introduction to NumPy and Matplotlib</a>
</div>

En el ejemplo, la variable `sumaFilas` contiene el resultado de la suma de todas las filas (`axis = 0`); mientras que la variable `sumaColumnas` contiene el resultado de la suma de todas las columnas (`axis = 1`) 

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b6.png?raw=true" width="35%">
</div>

In [ ]:
# En el arreglo totalFilas asigne el resultado de sumar todas las filas de la matriz7. 
# Muestre el arreglo totalFilas.

print("Matriz 7")
print(matriz7)

print("\nSuma de todas las filas (axis 0)")
totalFilas = np.sum(  , )

print(totalFilas)

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print("Matriz 7")
print(matriz7)

print("\nSuma de todas las filas (axis 0)")
totalFilas = np.sum( matriz7 , axis = 0)

print(totalFilas)
  </code></pre>
</details> 

In [ ]:
# En el arreglo totalColumnas asigne el resultado de sumar todas las columnas de la matriz8. 
# Muestre el arreglo totalColumnas.

print("Matriz 8")
print(matriz8)

print("\nSuma de todas las columnas (axis 1)")
totalColumnas = np.sum(  , )

print(totalColumnas)

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print("Matriz 8")
print(matriz8)

print("\nSuma de todas las columnas (axis 1)")
totalColumnas = np.sum( matriz8 , axis = 1)

print(totalColumnas)
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Archivos

Descargue el archivo [produccion.zip](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/produccion.zip). Descomprima la carpeta **produccion** y mueva la carpeta en el mismo directorio de este cuaderno.

## Carga de datos


Utilice la función [loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) para cargar los datos de un archivo de texto.

In [15]:
# En el arreglo zonas, cargue los datos de 'produccion/zonas.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

zonas = np.loadtxt('produccion/zonas.csv', delimiter = ',', dtype = str)

In [16]:
# Muestre el arreglo zonas
# Muestre el tamaño del arreglo zonas

tamanioZonas = zonas.shape
print(f"Zonas: {zonas}")
print(f"Tamaño de zonas: {tamanioZonas}")

Zonas: ['zona1' 'zona2' 'zona3' 'zona4' 'zona5' 'zona6']
Tamaño de zonas: (6,)


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
tamanioZonas = zonas.shape
print(f"Zonas: {zonas}")
print(f"Tamaño de zonas: {tamanioZonas}")
  </code></pre>
</details> 

In [17]:
# En el arreglo productos, cargue los datos de 'produccion/productos.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

productos = np.loadtxt('produccion/productos.csv', delimiter = ',', dtype = str)

In [18]:
# Muestre el arreglo productos
# Muestre el tamaño del arreglo productos

tamanioProductos = productos.shape
print(f"Productos: {productos}")
print(f"Tamaño de Productos: {tamanioProductos}")

Productos: ['Energía Vitalizante Xtreme' 'EcoLimpiaPro'
 'TurboTech Auriculares Inalámbricos' 'SuperBrillo Lavaplatos'
 'MaxProtección Crema Solar' 'UltraGourmet Mezcla de Especias'
 'SpeedyFresh Desodorante para Refrigerador' 'EcoBike Plegable'
 'BrillantePlus Limpiacristales' 'SúperAroma Ambientador de Lavanda'
 'MagnoFit Banda de Resistencia' 'MegaSnack Barritas Energéticas'
 'AquaBreeze Purificador de Aire' 'BioJardín Fertilizante Orgánico'
 'ZoomCam Cámara de Vigilancia HD']
Tamaño de Productos: (15,)


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
tamanioProductos = productos.shape
print(f"Productos: {productos}")
print(f"Tamaño de Productos: {tamanioProductos}")
  </code></pre>
</details> 

In [19]:
# En los arreglos octubre, noviembre y diciembre, cargue los datos de cada archivo con el nombre correspondiente
# cuyo delimitador es ',' y el tipo de dato (dtype) es in

octubre = np.loadtxt('produccion/octubre.csv', delimiter = ',', dtype = int)
noviembre = np.loadtxt('produccion/noviembre.csv', delimiter = ',', dtype = int)
diciembre = np.loadtxt('produccion/diciembre.csv', delimiter = ',', dtype = int)

In [25]:
# Muestre la matriz octubre

print(f"Octubre")
print(octubre)

Octubre
[[13  6  8  7 12 12]
 [13  6 11  8  8  5]
 [ 6 12 12 13 12  7]
 [ 6 12  7  4  6  4]
 [ 8 10  3 13  7  7]
 [ 5  4  5 14  2 11]
 [11  6 13  4  3 10]
 [ 2  9  7  3  3 10]
 [ 5 12  3  7 13 11]
 [ 9  7  8 10  5  8]
 [10 11 13  5  3  5]
 [12 11  6  2 10 12]
 [ 4  6 10  2  2  6]
 [ 3 12  5  6 12 14]
 [ 7  3 10 10 12  7]]


In [27]:
# Muestre el tamaño de la matriz octubre

tamanioOctubre = octubre.shape
print(f"Tamaño de Productos: {tamanioOctubre}")

Tamaño de Productos: (15, 6)


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
tamanioOctubre = octubre.shape
print(f"Tamaño de Productos: {tamanioOctubre}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Ejercicios

Para los siguientes ejercicios, considere que las matrices `octubre`, `noviembre` y `diciembre` corresponden a la cantidad de productos elaborados en los tres últimos los meses del año pasado. 

Las **filas** están directamente relacionados con los `productos` y las **columnas** están directamente relacionadas con las `zonas` de producción.

<br>
<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b8.png?raw=true" width="75%">
</div>

**Ejercicio 01:** Muestre la matriz resultante con la suma de los tres últimos meses

**Ejercicio 02:** Muestre el total (suma) de la producción del mes de octubre.

**Ejercicio 03:** Muestre el total (suma) de producción de los tres últimos meses

**Ejercicio 04:** Obtenga el total de producción por las zonas de la matriz con los tres últimos meses. 


**Ejercicio 05:** Grafique los nombres de las zonas _versus_ el total de producción por las zonas de la matriz con los tres últimos meses.

### Ejercicios - III

1. Muestre la suma total de producción de los tres últimos meses de la `zona4`
2. Muestre la suma total de producción de noviembre del producto `'SúperAroma Ambientador de Lavanda'`

In [ ]:
# Forma 1: Muestre la suma total de producción de los tres últimos meses de la zona4
mascaraZona4 = zonas == 'zona4'
mascaraZona4

In [ ]:
zonas[mascaraZona4]

In [ ]:
tresmeses[ 0: , mascaraZona4]

In [ ]:
total = np.sum(tresmeses[0:, mascaraZona4])

print('Suma total de producción de los tres últimos meses de la zona4')
print(total)

In [ ]:
# Forma 2: Muestre la suma total de producción de los tres últimos meses de la zona4

zona4 = tresmeses[0:,3]
total = np.sum(zona4)
print('Suma total de producción de los tres últimos meses de la zona4')
print(total)

In [ ]:
# Muestre la suma total de producción de noviembre del producto 'SúperAroma Ambientador de Lavanda'

mascaraProducto = productos == 'SúperAroma Ambientador de Lavanda'
print(mascaraProducto)

In [ ]:
noviembre[ mascaraProducto , 0: ]

In [ ]:
total = np.sum(noviembre[ mascaraProducto , 0: ])
print("El total de producción de noviembre del producto 'SúperAroma Ambientador de Lavanda'")
print(total)

### Ejercicios - IV

1. Muestre el nombre del producto con la mayor suma total de producción del mes de diciembre.
2. Muestre el nombre de la zona con la menor suma total de producción del mes de noviembre.

In [ ]:
diciembre

In [ ]:
sumaPorProducto = np.sum(diciembre, axis = 1)
sumaPorProducto

In [ ]:
indiceMayor = np.argmax(sumaPorProducto)
indiceMayor

In [ ]:
print("Nombre del producto con la mayor suma total de producción del mes de diciembre")
print(productos[indiceMayor])

In [ ]:
print("Nombre de la zona con la menor suma total de producción del mes de noviembre.")
sumaPorZonas = np.sum(noviembre, axis = 0)
indiceMenor = np.argmin(sumaPorZonas)
print(zonas[indiceMenor])

[Regresar a la TC](#Tabla-de-Contenidos)