## Matrices

Las matrices son una estructura de datos bidimencional donde los elementos se organizan en filas y columnas. Python no tiene soporte integrado para matrices; sin embargo, [NumPy](https://numpy.org/) permite el manejo de matrices como **lista dentro de listas**.

Ejemplo de esto: 

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/matriz.webp?raw=true" width="40%">
    Fuente: <a href="https://pythondiario.com/2019/01/matrices-en-python-y-numpy.html">Matrices en Python y NumPy</a>
</div>

Esta matriz es una matriz de 3x4 porque tiene 3 filas y 4 columnas. 

Revise la documentación en [NumPy documentation](https://numpy.org/doc/stable/).

## Importar librerías externas


In [3]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt

import numpy as np
import matplotlib.pyplot as plt

## De listas de listas a matrices

Para crear [una matriz a partir de una lista de listas](https://www.geeksforgeeks.org/convert-python-nested-lists-to-multidimensional-numpy-arrays/), utilizaremos la función **array**.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_lol.png?raw=true" width="40%">
</div>

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_mat.png?raw=true" width="35%">
</div>


In [39]:
# Convierta la lista de listas en una matriz 
# Muestre por pantalla la matriz

listaDeLista = [[1, 4, 5], [-5, 8, 9]]

matriz = 


## Filas y Columnas

Numpy utiliza el o los índices de las **filas** y de las **columnas** para acceder a un elemento o a un grupo de elementos en una matriz.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_indices.png?raw=true" width="20%">
</div>



Para acceder a todos los elementos en la primera fila: [ **índice 0**, **rebanada desde 0: hasta el final** ] 


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_fila0.png?raw=true" width="30%">
</div>


In [ ]:
# Muestre la fila 0 de la matriz


In [ ]:
# Muestre la fila 1 de la matriz


Para acceder a todos los elementos en la segunda columna: [ **rebanada desde 0: hasta el final**, **índice 1** ] 


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/mat_columna1.png?raw=true" width="30%">
</div>


In [49]:
# Muestre, por separado, cada columna de matriz


In [8]:
listaDeLista = [[1, 7, 0], [ 6, 2, 5]] 
print("Lista de lista: ")
print(listaDeLista)

Lista de lista: 
[[1, 7, 0], [6, 2, 5]]


In [42]:
matriz = np.array(listaDeLista)
print("Matriz: ")
print(matriz)

Matriz: 
[[ 1  4  5]
 [-5  8  9]]



```python
índices:
          columna
          0  1  2
fila      ↓  ↓  ↓
 0   → [[ 1  4  5]
 1   →  [-5  8  9]]
```


In [48]:
columna1 = matriz[0:,1]
print("Columna 1: ", columna1)

Columna 1:  [4 8]


In [37]:
## Matriz con valores aleatorios

np.random.rand(3,2)

array([[0.97005452, 0.43312126],
       [0.66469674, 0.45413063],
       [0.34282564, 0.95779111]])