## Importar librerías externas

In [1]:
# Importe la librería numpy, con: import numpy as np
# Importe la libreria matplotlib, con: import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt

## Arreglos y matrices 

Convierta las listas en arreglos (1-dimensión) y matrices (2-dimensiones).

In [2]:
# Convierta las listas en arreglos

lista1 = [11, 12,  9,  3, 14,  9]
lista2 = [ 6, 11, 10, 12,  9, 10]

arreglo1 = np.array(lista1)
arreglo2 = np.array(lista2)

In [3]:
# Convierta las listas de listas en matrices

listaDelistas1 = [[14,  5,  4, 13,  8, 14],
                  [10,  2,  9,  9,  3,  4],
                  [ 9,  4, 11,  7,  9, 13],
                  [14,  5, 14, 12, 13,  9],
                  [12,  3,  5,  5,  4,  8]]

listaDelistas2 = [[14,  6,  2,  5, 10,  8],
                  [13, 11, 14, 11,  4, 10],
                  [14, 13,  3, 14,  5,  7],
                  [ 2,  2,  8, 14,  2,  4],
                  [11,  6, 12,  3,  4,  2]]

matriz1 = np.array(listaDelistas1)
matriz2 = np.array(listaDelistas2)

## Operaciones por elementos

### Con un escalar

Numpy permite optimizar las operaciones entre [un arreglo y un escalar](https://scipy-lectures.org/intro/numpy/operations.html#id2); por ejemplo, el `arreglo3` contiene el resultado de la suma de cada elemento del `arreglo1` con `5.2`.



<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b1.png?raw=true" width="35%">
</div>

In [4]:
# En arreglo4 asigne el resultado de sumar arreglo2 y 4. Muestre el resultado de arreglo4.

In [5]:
# En arreglo5 asigne el resultado de multiplicar arreglo1 y 2.3. Muestre el resultado de arreglo5.

In [6]:
# En arreglo6 asigne el resultado de restar arreglo2 y 2.3. Muestre el resultado de arreglo6.

### Entre arreglos

NumPy proporciona una amplia gama de [operaciones que se pueden realizar entre arreglos](https://www.programiz.com/python-programming/numpy/basic-array-operations). En el ejemplo, la multiplicación entre `arreglo1` y `arreglo2`ocurre entre cada elemento correspondiente, dado que tienen el mismo tamaño.


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b2.png?raw=true" width="35%">
</div>


In [7]:
# En arreglo8 asigne el resultado de dividir arreglo1 y arreglo4. Muestre el arreglo8.

In [8]:
# En arreglo9 asigne el resultado de restar arreglo2 y arreglo5. Muestre el arreglo9.

In [9]:
# En arreglo10 asigne el resultado de sumar arreglo5 y arreglo6. Muestre el arreglo10.

## Operaciones matriciales

NumPy provee de operaciones matriciales como suma, multiplicación y elevación de elementos a una determinada potencia. El empleo de matrices nos permite ejecutar operaciones algebraicas, lo que nos permite ejecutar numerosas operaciones con grandes cantidades de datos de manera efectiva. [How to Implement Different Operations on Matrices in NumPy?](https://www.scaler.com/topics/numpy-implement-different-operations-on-matrix/) muestran las operaciones más comunes entre matrices mediante ejemplos.

In [34]:
matriz1

array([[14,  5,  4, 13,  8, 14],
       [10,  2,  9,  9,  3,  4],
       [ 9,  4, 11,  7,  9, 13],
       [14,  5, 14, 12, 13,  9],
       [12,  3,  5,  5,  4,  8]])

In [31]:
sumaFilas = np.sum(matriz1, axis = 0 )
print("Suma de las filas")
print(sumaFilas)

Suma de las filas
[59 19 43 46 37 48]


In [32]:
sumaColumnas = np.sum(matriz1, axis = 1 )
print("Suma de las columnas")
print(sumaColumnas)

Suma de las columnas
[58 37 53 67 37]


### Operaciones con un escalar

En el ejemplo, la `matriz3` contiene el resultado de multiplicar `1.12` y `matriz1`, al multiplicar cada elemento por el escalar.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b3.png?raw=true" width="30%">
</div>

In [17]:
# En matriz4 asigne el resultado de sumar matriz2 y 3.2. Muestre el matriz4.

In [18]:
# En matriz5 asigne el resultado de dividir matriz1 para 2. Muestre el matriz5.

### Operaciones matriciales

Para matrices de igual número de filas y columnas, es posible realizar las operaciones matemáticas básicas para cada elemento de las matrices. Por ejemplo, `matriz6` contiene el resultado de restar `matriz1` y `matriz2`.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b4.png?raw=true" width="30%">
</div>

In [19]:
# En matriz7 asigne el resultado de sumar matriz2 y matriz1. Muestre el matriz7.

In [20]:
# En matriz8 asigne el resultado de multiplicar matriz2 y matriz1. Muestre el matriz8.

### Operaciones de todos los elementos

La función [np.sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) se utiliza para determinar la suma de todos los elementos de la matriz NumPy.

<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b5.png?raw=true" width="45%">
</div>

In [21]:
# En total7 asigne el resultado de sumar todos los elementos de la matriz7. Muestre el total7.

In [22]:
# En total8 asigne el resultado de sumar todos los elementos de la matriz8. Muestre el total8.

### Operaciones por columnas o por filas

La función de [np.sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) NumPy tiene varios parámetros que le permiten controlar el comportamiento de la función.






<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b7.png?raw=true" width="35%">
    Fuente: <a href="https://sebastianraschka.com/blog/2020/numpy-intro.html">Scientific Computing in Python: Introduction to NumPy and Matplotlib</a>
</div>


<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b6.png?raw=true" width="35%">
</div>

## Operaciones entre arreglos y matrices

## Archivos

Descargue el archivo [produccion.zip](https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/produccion.zip). Descomprima la carpeta **produccion** y mueva la carpeta en el mismo directorio de este cuaderno.

## Carga de datos


Utilice la función [loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) para cargar los datos de un archivo de texto.

In [23]:
# En la variable zonas, cargue los datos de 'produccion/zonas.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

zonas = np.loadtxt('produccion/zonas.csv', delimiter=",", dtype=str)

In [24]:
# En la variable productos, cargue los datos de 'produccion/productos.csv', 
# cuyo delimitador es ',' y el tipo de dato (dtype) es str

productos = np.loadtxt('produccion/productos.csv', delimiter=",", dtype=str)

In [25]:
# En las variables octubre, noviembre y diciembre, cargue los datos de cada archivo con el nombre correspondiente
# cuyo delimitador es ',' y el tipo de dato (dtype) es in

octubre = np.loadtxt('produccion/octubre.csv', delimiter=",", dtype=int)

## Ejercicios

Para los siguientes ejercicios, considere que las matrices `octubre`, `noviembre` y `diciembre` corresponden a las ventas (cientos de dólares) de tres últimos los meses del año pasado. Las filas corresponden a los `productos` y las columnas corresponden a las `zonas` de venta.

<br>
<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/arr_b8.png?raw=true" width="75%">
</div>